generator:
  class: sfPropelGenerator
  param:
    model_class:           BusinessUnit
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              BusinessUnit
    plural:                BusinessUnits
    route_prefix:          business_unit
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        object_actions:
          projectReport:   { label: Отчет по проектам, action: projectReport }
          currentExpenses: { label: Текущие расходы, action: currentExpenses }
          cashFlow:        { label: Cashflow, action: cashflow }
          _edit:        ~
          _delete:      ~
      filter: 
        class: false
      form:    ~
      edit:    ~
      new:     ~
