generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_propel_route:     1

    config:
      fields:
        password_again: { label: "Password (again)" }
        created_at:     { label: "Дата регистрации" }
        email:          { label: "E-mail"}
       # created_at:     { date_format: "dd/MM/y" }
        
      filter:
        class: false

      list:
        title:              User list
        peer_method:        doSelectJoinProfile
        display:            [=username, email, first_name, last_name, phone, is_active, created_at]

      form:
        class:                      UserAdminForm
        display:
          "NONE":                   [username, password, password_again, first_name, last_name, email, phone, address, bio]
          "Permissions and groups": [is_active, sf_guard_user_permission_list, user_business_unit_list]

      edit:
        title: Editing User "%%username%%"

      new:
        title: New User
