# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [/css/bootstrap.css, /css/bootstrap-responsive.css]

  javascripts:    [/js/jquery-1.4.4.min.js, /js/bootstrap.js, /js/jshashtable-2.1.js, /js/jquery.numberformatter-1.2.3.js]

  has_layout:     true
  layout:         layout
