generator:
  class: sfPropelGenerator
  param:
    model_class:           Tender
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Tender
    plural:                Tenders
    route_prefix:          tender
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
        display: [id, name, budget, amount, status]
      filter:  ~
      form:    ~
      edit:    ~
      new:
        title:     Новый тендер
