generator:
  class: sfPropelGenerator
  param:
    model_class:           ExpencesType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ExpencesType
    plural:                ExpencesTypes
    route_prefix:          expences_type
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
